NUM_KEY_VALUE_PAIRS=9
NUM_NODES=3
KEY_SIZE=24
VALUE_SIZE=4096
TOTAL_OPERATIONS=100
OP_FILE="\"operations\""
DATASET_FILE="\"./dataset.txt\""

# enum DistributionType {
#     RANDOM_DISTRIBUTION,
#     PARTITIONED_DISTRIBUTION,
#     ZIPFIAN_DISTRIBUTION,
#     ZIPFIAN_PARTITIONED_DISTRIBUTION
# };
DISTRIBUTION_TYPE = RANDOM_DISTRIBUTION

# Key Distribution setting
HOT_KEY_PERCENTAGE = 0.20
HOT_KEY_ACCESS_PERCENTAGE = 0.80